# Require any additional compass plugins here.

#################
# Sass Settings -- Generated by Compass
#################

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "public/css"
sass_dir = "sass"
images_dir = "public/images"
javascripts_dir = "public/js"

# CSS Output
output_style = :compressed # Minfies the CSS. Other options include :expanded, :nested or :compact.
line_comments = false
