# Config information for our database. This is a rails pattern, but it's
# enabled for sinatra through the sinatra-activerecord gem.

# @todo: Remove production db info (including password)
# I think the production stuff isn't really necessary, since it's overwritten by the
# DATABASE_URL environment variable. See:
# https://www.digitalocean.com/community/articles/how-to-use-dokku-plugins-to-access-additional-functionality

development:
  adapter: sqlite3
  database: blog.db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: db
  pool: 5
  username: root
  password: XXXXXXXXXXXXXX
  host: ###.##.##.#
  port: 49153
